# Site settings
title: Felix Assion blog
email: 
description: "Artificial Intelligence."
baseurl: ""
url: "http://ixi90.github.io"
github_username:  IXI90

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
