# Site settings
title: Neurocat blog
email: 
description: "Artificial Intelligence."
baseurl: ""
url: "http://f37.github.io"
github_username:  f37

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
